"""ubah_shift_enum_dari_varchar_ke_pagi_siang

Revision ID: 6fc05a470d47
Revises: f52b3e7048d0
Create Date: 2026-01-07 03:13:17.854020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fc05a470d47'
down_revision = 'f52b3e7048d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_settings', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               type_=sa.Enum('PAGI', 'SIANG'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('nama'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nama'), ['nama'], unique=True)
        batch_op.alter_column('nama',
               existing_type=sa.Enum('PAGI', 'SIANG'),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
