"""initial schema

Revision ID: f52b3e7048d0
Revises: 
Create Date: 2025-12-31 00:01:41.133287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52b3e7048d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=False),
    sa.Column('jam_masuk', sa.Time(), nullable=False),
    sa.Column('jam_pulang', sa.Time(), nullable=False),
    sa.Column('toleransi_menit', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=64), nullable=False),
    sa.Column('nama', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('foto_profil', sa.String(length=255), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('HADIR', 'TERLAMBAT', 'IZIN', 'ALPA', 'DITOLAK'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('liveness_ok', sa.Boolean(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'tanggal', name='unique_daily_attendance')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_tanggal', ['tanggal'], unique=False)

    op.create_table('face_encodings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.JSON(), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.String(length=255), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('bukti_foto', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISETUJUI', 'DITOLAK'), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('idx_leave_tanggal', ['tanggal_mulai', 'tanggal_selesai'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_tanggal')

    op.drop_table('leave_requests')
    op.drop_table('face_encodings')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_tanggal')

    op.drop_table('attendances')
    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('shift_settings')
    # ### end Alembic commands ###
